version: '3.2'

services:
    test:
        build:
            context: ./behat
            dockerfile: Dockerfile.behat
        depends_on:
            - chrome
            - localstack-init
            - mock-sirius-integration
        volumes:
            - ./behat/tests:/var/www/tests
            - ./behat/snapshots:/tmp/html
        env_file:
            - ./behat/test.env
            - ./behat/.env

#    selenium-hub:
#        image: selenium/hub:3.141.59-20201119
#        ports:
#            - "4444:4444"

#    chrome:
#        image: selenium/node-chrome:3.141.59-20201119
#        volumes:
#            - /dev/shm:/dev/shm
#        depends_on:
#            - selenium-hub
#        environment:
#            - HUB_HOST=selenium-hub
#            - HUB_PORT=4444

    chrome:
        build:
            context: ./behat
            dockerfile: Dockerfile.chrome
        cap_add:
            - SYS_ADMIN
        ports:
            - 9222:9222

    npm:
        image: node:8-alpine
        working_dir: /app
        volumes:
            - ./client/:/app
        entrypoint: npm
        environment:
            NODE_ENV: production

    composerapi:
        image: composer:1.10.16
        volumes:
            - ./api/:/app

    composerfront:
        image: composer:1.10.16
        volumes:
            - ./client/:/app

    frontend:
        env_file:
            - ./behat/test.env
            - .env

    admin:
        env_file:
            - ./behat/test.env
            - .env

    mock-sirius-integration:
        image: muonsoft/openapi-mock:latest
        ports:
            - 6060:8080
        environment:
            - OPENAPI_MOCK_SPECIFICATION_URL=https://raw.githubusercontent.com/ministryofjustice/opg-data-deputy-reporting/master/lambda_functions/v2/openapi/deputy-reporting-openapi.yml
